#!/usr/bin/bash

code --install-extension 4ops.terraform
code --install-extension adamhartford.vscode-base64
code --install-extension ArturoDent.custom-language-syntax
code --install-extension Artymaury.template-finder
code --install-extension aws-scripting-guy.cform
code --install-extension be5invis.toml
code --install-extension bibhasdn.unique-lines
code --install-extension charliermarsh.ruff
code --install-extension coolbear.systemd-unit-file
code --install-extension cybai.yaml-key-viewer
code --install-extension darkriszty.markdown-table-prettify
code --install-extension EditorConfig.EditorConfig
code --install-extension equinusocio.vsc-material-theme-icons
code --install-extension eriklynd.json-tools
code --install-extension esbenp.prettier-vscode
code --install-extension ExodiusStudios.comment-anchors
code --install-extension fabiospampinato.vscode-diff
code --install-extension foxundermoon.shell-format
code --install-extension GitHub.github-vscode-theme
code --install-extension GlenBuktenica.unicode-substitutions
code --install-extension golang.go
code --install-extension hangxingliu.vscode-systemd-support
code --install-extension hashicorp.terraform
code --install-extension hoovercj.vscode-power-mode
code --install-extension j-zeppenfeld.tab-indent-space-align
code --install-extension janisdd.vscode-edit-csv
code --install-extension jkiviluoto.tws
code --install-extension mdickin.markdown-shortcuts
code --install-extension mechatroner.rainbow-csv
code --install-extension mgesbert.python-path
code --install-extension mhutchie.git-graph
code --install-extension mongodb.mongodb-vscode
code --install-extension mousavian.ssh-config-syntax-highlighter
code --install-extension mrmlnc.vscode-duplicate
code --install-extension ms-azuretools.vscode-docker
code --install-extension ms-kubernetes-tools.vscode-kubernetes-tools
code --install-extension ms-python.black-formatter
code --install-extension ms-python.isort
code --install-extension ms-python.python
code --install-extension ms-python.vscode-pylance
code --install-extension ms-toolsai.jupyter
code --install-extension ms-toolsai.vscode-jupyter-cell-tags
code --install-extension ms-toolsai.vscode-jupyter-slideshow
code --install-extension ms-vscode.live-server
code --install-extension ms-vscode.sublime-keybindings
code --install-extension naumovs.color-highlight
code --install-extension nidu.copy-json-path
code --install-extension njpwerner.autodocstring
code --install-extension njqdev.vscode-python-typehint
code --install-extension oderwat.indent-rainbow
code --install-extension PascalReitermann93.vscode-yaml-sort
code --install-extension PKief.material-icon-theme
code --install-extension PKief.material-product-icons
code --install-extension redhat.ansible
code --install-extension redhat.vscode-yaml
code --install-extension richie5um2.vscode-statusbar-json-path
code --install-extension RobbOwen.synthwave-vscode
code --install-extension RoscoP.ActiveFileInStatusBar
code --install-extension ruiquelhas.vscode-uppercase
code --install-extension ryanluker.vscode-coverage-gutters
code --install-extension sadesyllas.explorer-excluded-files
code --install-extension samuelcolvin.jinjahtml
code --install-extension secsamdev.grok
code --install-extension sleistner.vscode-fileutils
code --install-extension sourcery.sourcery
code --install-extension thegtproject.hoverhex
code --install-extension Tim-Koehler.helm-intellisense
code --install-extension timonwong.shellcheck
code --install-extension tsandall.opa
code --install-extension Tyriar.sort-lines
code --install-extension vscode-icons-team.vscode-icons
code --install-extension Wattenberger.footsteps
code --install-extension wayou.vscode-todo-highlight
code --install-extension yzhang.markdown-all-in-one
code --install-extension ZainChen.json
